server:
  port: 8090

logging:
#  path: c:\temp\
  level:
    org.springframework.web: DEBUG
    com.spring: DEBUG

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/shoppingmall?useUnicode=true&charaterEncoding=utf-8&interactiveClient=true&autoReconnect=true&autoReconnectForPools=true&useSSL=false
  username: manager
  password: hamee
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000
  
mapConfig:
  map1:
    key1: config map1 key 1.
    key2: config map1 key 2.
  map2:
    key1: config map2 key 1.
    key2: config map2 key 2.

strConfig:
  strValue: config string


---
#java -jar -Dspring.profiles.active=dev
spring:
  profiles: dev

server:
  port: 8090

logging:
  path: /home/hameeiface/cert/logs/
  level:
    org.springframework.web: DEBUG
    jp.hamee: DEBUG

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_name?useUnicode=true&charaterEncoding=utf-8&interactiveClient=true&autoReconnect=true&autoReconnectForPools=true&useSSL=false
  username: db_user
  password: db_password
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000
  
mapConfig:
  map1:
    key1: config map1 key 1.
    key2: config map1 key 2.
  map2:
    key1: config map2 key 1.
    key2: config map2 key 2.

strConfig:
  strValue: config string
  
---
#java -jar -Dspring.profiles.active=prd
spring:
  profiles: prd

server:
  port: 8080

logging:
  path: /home/hameeiface/cert/logs/
  level:
    org.springframework.web: INFO
    jp.hamee: INFO

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_name?useUnicode=true&charaterEncoding=utf-8&interactiveClient=true&autoReconnect=true&autoReconnectForPools=true&useSSL=false
  username: db_user
  password: db_password
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000
  
mapConfig:
  map1:
    key1: config map1 key 1.
    key2: config map1 key 2.
  map2:
    key1: config map2 key 1.
    key2: config map2 key 2.

strConfig:
  strValue: config string
